### ISSUE TITLE
etag should be uint64

### ISSUE THREAD

**Issue by mdutoo** [erocci/erocci#40]

**Comment by cgourdin** [comment]
eTag should'nt be uint64 but String value (md5 ?) like this : b76b8c36b40cfbfbeac66779ceb8334aadeb5462 
ref : [https://www.ogf.org/OGF34/materials/2433/interop-cloud-occi-ogf34.pdf](url)

**Comment by jeanparpaillon** [comment]
etag serve for caching purpose, to know if an entity has changed. An etag can esaily be generated from an integer, but an integer can server other purpose as it can be ordered (in addition to be compared). That's why erocci asks backend for a 'serial' number rather than an etag.

That being said, a uint64 would be better than an uint32 and the API should be updated as noted by Marc, while priority is low.

**Comment by cgourdin** [comment]
Etag is rendered as alphanumeric on all other servers, i understand the use of uint32 (or 64 programmatically) but this is not done on others and the specs i found didn't mention numbers etag. if i understand correctly, you use the serial number for ordering purposes. Which case exactly use that info ? Loading collections ? I think it's better to use alpha tag as it's a standard and OCCI specification way. See specification GFD.185 section 3.7.2 p25-p26 on rendering a resource example.

**Comment by jeanparpaillon** [comment]
I think there is a misunderstanding about what we're talking about:
* etag is the data rendered on the HTTP API. Obvisouly, it is a string, as HTTP spec defines it
* serial is the internal serial number of the resource, existing only between erocci core and backends

While there is a link between them (serial being used for generating etag), the serial is something simpler (for generating) and more compact (for storing).
uint64 -> 4 bytes, upgrade = serial++
etag -> 32 bytes, uprgade = generates a new uuid or hashing the resource

So, except for really sound reason, I would *really* prefer identifying resource versions with a serial number rather than a text etag (uuid), while rendering it as a fully conform etag _wherever required_ (HTTP is not supposed to be the only protocol on top of erocci.

**Comment by jeanparpaillon** [comment]
New backend API; serial are strings
