### ISSUE TITLE
Full Update of a resource instance

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#57]
$ curl -i -v http://malmo.lizenn.net:8080/collections/user/Merle 
...
HTTP/1.1 200 OK
...
category: user; scheme="http://example.org/occi/test#"; class="kind"
x-occi-attribute: blog.user.name="Merle"
x-occi-attribute: blog.user.email="merle@occiware.org"
x-occi-attribute: occi.core.id=87254351

$ curl -i -v http://malmo.lizenn.net:8080/collections/user/Merle -X PUT -H 'Content-Type: text/occi' -H 'X-OCCI-Attribute: occi.core.title="Merle"'
...
HTTP/1.1 409 Conflict
...

Why 409 is returned?

**Comment by jeanparpaillon** [comment]
PUT verb "creates a new or replace an existing".
_My interpretation_ is that entity id must be the same, which is not the case in your request:
1st one: occi.core.id=87254351
2nd one: (empty)

The problem in the spec is an entity id is not clearly defined: it may be the URL and/or the occi.core.id attribute.

Due to the ambiguity of the spec, I would say my implementation is correct but the spec should be clearer. 
See also:
https://www.ogf.org/pipermail/occi-wg/2016-April/003743.html
